### ISSUE TITLE
Environment Variables not available

### ISSUE THREAD

**Issue by MirkoLenz** [netlify/netlify-plugin-gatsby#83] opened 2021-07-11 19:39 UTC
**Describe the bug**

Gatsby functions processed with this plugin do not seem to have access to the environment variables specified on the Netlify admin page (`settings/deploys#environment`). When sending one of the variables to the frontend via JSON, it is 'null'.

**Steps to reproduce**

1. Create a new Gatsby function.
2. Add an environment variable in the Netlify admin.
3. Use this variable in the function.

**Expected behavior**

The provided environment variables are available in the Gatsby function (i.e., can be accessed via `process.env.VARIABLE_NAME`).

**Configuration**

Not applicable.

**Environment**

Tested on Netlify directly.

**Screenshots**

Not applicable.

**Can you submit a pull request?**

No.

**Comment by ascorbic** [comment] 2021-07-14 10:56
Hi. I'm unable to reproduce this. Here's the repo I tested with: https://github.com/ascorbic/gatsby-fun

- I created a gatsby site using `yarn create gatsby`
- I added a file `src/api/env-variables.js`:
```js
export default function handler(req, res) {
  res.send(process.env.VARIABLE_NAME);
}
```
- I set `VARIABLE_NAME` in the UI to the value `"set in UI"`
![image](https://user-images.githubusercontent.com/213306/125611011-2b2dfa1b-1891-4910-8b83-82d077989f60.png) 
- I deployed to Netlify, adding the Essential Gatsby plugin
- I checked the output of the function: https://gifted-albattani-b827fe.netlify.app/api/env-variables

Could you provide a minimal reproduction please?

**Comment by MirkoLenz** [comment] 2021-07-16 08:06
Thank you for your investigation! I will try to come up with a reproduction case in the next days. In the meantime, I resolved this issue for my current project with the following plugin: https://www.npmjs.com/package/netlify-plugin-inline-functions-env.

**Comment by ascorbic** [comment] 2021-08-02 14:18
I'm closing this for now. If you manage to reproduce, please open a new issue.

**Closed by ascorbic** 2021-08-02 14:18 UTC
Labels: bug, status: needs reproduction
